name: "Build"

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion:
          - 1.4.0
          - binary:stable
        os:
          - windows-latest
          # - macos-latest
          - ubuntu-latest
    name: ${{ matrix.os }} - ${{ matrix.nimversion }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v4
        with:
          version: ${{ matrix.nimversion }}
      - run: nim --version
      - name: Refresh packages + install dependencies
        run: |
          nimble refresh
          nimble install -d
      - name: Run all tests
        run: nimble --silent test